// frontend/src/App.tsx
import React from "react";
import "./App.css";
import Header from "./components/Header";
import Toolbar from "./components/Toolbar";
import Playground from "./components/Playground";

export default function App() {
  return (
    <div className="App">
      <Header />
      <Toolbar />
      <Playground />
    </div>
  );
}

// frontend/src/App.vue
<template>
  <v-app>
    <Header />

    <v-main>
      <Playground />
    </v-main>
  </v-app>
</template>

<script>
import Header from "./components/Header.vue";
import Playground from "./components/Playground.vue";

export default {
  name: "App",

  components: {
    Header,
    Playground,
  },

  data: () => ({
    //
  }),
};
</script>
